version: "3.7"

services:
  web:
    build: .
    env_file:
      - .env

  nginx:
    image: nginx
    volumes:
      - ./docker-nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    depends_on:
      - web
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_PORT=80
